### ISSUE TITLE
Doesnt have access to to pc_all.opt.starpak

### ISSUE THREAD

**Issue by ttv-1nf1n1ty** [zxcPandora/Titanfall2-SkinTool#13]
![image_2022-09-21_143524751](https://user-images.githubusercontent.com/84960946/191493955-854c8ca4-f9bd-4966-b66d-802fe7ed8d7c.png)

**Comment by zxcPandora** [comment]
You can check the file properties by right-clicking on the file and choosing **Properties**. If the **Read-only** attribute is checked, you can uncheck it and click **OK**.
