### ISSUE TITLE
Hey PROBLEM!!!!!!

### ISSUE THREAD

**Issue by AkyZa141** [zxcPandora/Titanfall2-SkinTool#16]
It says that theres occured an error in deleting the files, plz help

**Comment by zxcPandora** [comment]
@AkyZa141  Tool will create a folder named `SaveFolder`  in the tool's root to temporaryin save skin  .
And will try to delete it after installed the skin.
It's not a particularly serious problem.
You can check this folder to found out which program is using this.

**Comment by zxcPandora** [comment]
2 weeks no reply,so close this issue
