### ISSUE TITLE
Addon To Mod Manager

### ISSUE THREAD

**Issue by BigSpice** [zxcPandora/Titanfall2-SkinTool#2]
Dear zxcPandora,
This is a request to make use of your existing source code to understand and code the Skin editor i have in development for the Mod manager. 

***I do not intend to reverse engineer and take credit for any of your methods.
I do not intend to create a replacement to your tool.***

I hope you can grant me the permission to continue and release this feature. 
To the Titanfall2 Community, to continue to flourish and grow past its glory days.

Your Sincerely,

Juicy.

**Comment by zxcPandora** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在百度贴吧潜水中，无法亲自回复您的邮件。我将在百度贴吧潜水结束后，尽快给您回复。

**Comment by zxcPandora** [comment]
> Dear zxcPandora, This is a request to make use of your existing source code to understand and code the Skin editor i have in development for the Mod manager.
> 
> _**I do not intend to reverse engineer and take credit for any of your methods. I do not intend to create a replacement to your tool.**_
> 
> I hope you can grant me the permission to continue and release this feature. To the Titanfall2 Community, to continue to flourish and grow past its glory days.
> 
> Your Sincerely,
> 
> Juicy.

that's nothing,most welcome~
Good lucky for your work~
