### ISSUE TITLE
Issue with removing skins.

### ISSUE THREAD

**Issue by G0zzy121** [zxcPandora/Titanfall2-SkinTool#3]
So a major issue i've had is with some of the player model skins as I am unable to delete them or remove them from the Skin-tool. If you have any idea on how you're able to remove the skins please let me know.

**Comment by zxcPandora** [comment]
delete this loop that check the pilot: (https://github.com/zxcPandora/Titanfall2-SkinTool/blob/c4903d03ca45677e33043b4e6b19bb94bb231ccb/MainWindow.cs#L152)
this loop in the frontend loop should be saved:(https://github.com/zxcPandora/Titanfall2-SkinTool/blob/c4903d03ca45677e33043b4e6b19bb94bb231ccb/MainWindow.cs#L161)

delete this function:(https://github.com/zxcPandora/Titanfall2-SkinTool/blob/c4903d03ca45677e33043b4e6b19bb94bb231ccb/MainWindow.cs#L373)

delete these data:(https://github.com/zxcPandora/Titanfall2-SkinTool/tree/master/Titanfall2/PilotData)

**Comment by zxcPandora** [comment]
> So a major issue i've had is with some of the player model skins as I am unable to delete them or remove them from the Skin-tool. If you have any idea on how you're able to remove the skins please let me know.

delete this loop that check the pilot: (https://github.com/zxcPandora/Titanfall2-SkinTool/blob/c4903d03ca45677e33043b4e6b19bb94bb231ccb/MainWindow.cs#L152)
this loop in the frontend loop should be saved:(https://github.com/zxcPandora/Titanfall2-SkinTool/blob/c4903d03ca45677e33043b4e6b19bb94bb231ccb/MainWindow.cs#L161)

delete this function:(https://github.com/zxcPandora/Titanfall2-SkinTool/blob/c4903d03ca45677e33043b4e6b19bb94bb231ccb/MainWindow.cs#L373)

delete these data:(https://github.com/zxcPandora/Titanfall2-SkinTool/tree/master/Titanfall2/PilotData)
